# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsimage',
            old_name='product',
            new_name='news',
        ),
    ]
